import "sample/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { LpNavbar1 } from "sample/components/pro-blocks/landing-page/lp-navbars/lp-navbar-1";

export const metadata: Metadata = {
  title: "My First Menu App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/openhunts.svg" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <LpNavbar1 />
        {children}
      </body>
    </html>
  );
}
